
FROM elasticsearch:8.5.1
# FROM debian:11.6


# RUN apt-get update

# # WORKDIR /elastic

# # RUN apt-get install curl gnupg apt-transport-https -y
# # RUN apt-get install -y wget

# RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list


