version: "3.2"
services:

  elasticsearch:
    container_name: elastic-web
    image: elastic-web
    build: ./elastic
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: 1g
    healthcheck:
      test: curl -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 8s
      timeout: 5s
      retries: 10
    ports:
      - ${ELASTIC_H_PORT}:9200  
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data

  backend:
    container_name: ${DOCKER_APP_NAME}
    build: ./backend/service
    image: fastapi-app
    restart: always
    ports:
      - 8000:80
    environment:
      - ELASTIC_INDEX=${ELASTIC_INDEX}
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_H_PORT=9200
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      elasticsearch:
        condition: service_healthy

  web:
    container_name: frontend-search
    image: frontend-search
    build: ./web
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - 8080:80
    depends_on:
      backend:
        condition: service_started
 
  # kibana:
  #   image: 'kibana:8.5.1'
  #   container_name: 'kibana'
  #   ports:
  #     - 5601:5601
  #   environment:
  #     SERVER_NAME: kibana1
  #     ELASTICSEARCH_URL: http://elasticsearch:9200


# volumes:
#   elasticsearch-data:
#     driver: local
